src/Entity/Magazine.php
<?php

namespace App\Entity;


use App\Entity\Titre;
use App\Entity\Redachef;
use App\Entity\Iconographique;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MagazineRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;



#[ORM\Entity(repositoryClass: MagazineRepository::class)]
/**  @ORM\Table(name="magazine", indexes={@ORM\Index(columns={"code_affaire", "code_affaire_en_clair"}, flags={"fulltext"})}) */

class Magazine
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 63)]
    private $code_affaire;

    #[ORM\Column(type: 'string', length: 255)]
    private $code_affaire_en_clair;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $date_de_bouclage;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $date_de_parution;

    #[ORM\Column(type: 'string', length: 127, nullable: true)]
    private $titre_en_clair;

    #[ORM\Column(type: 'float', length: 63, nullable: true)]
    private $nb_de_page_redactionnelle;

    #[ORM\ManyToOne(targetEntity: Titre::class, inversedBy: 'magazines')]
    #[ORM\JoinColumn(nullable: true)]
    private $titre;

    #[ORM\Column(type: 'float', length: 63, nullable: true)]
    private $chiffre_affaire;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_de_parution_set_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_de_bouclage_set_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $nb_de_page_redactionnelle_set_at;

    #[ORM\OneToMany(mappedBy: 'magazine', targetEntity: Redachef::class)]
    private $redachefs;

    #[ORM\OneToMany(mappedBy: 'magazine', targetEntity: Iconographique::class)]
    private $iconographiques;

    #[ORM\OneToMany(mappedBy: 'magazine', targetEntity: PigisteClient::class)]
    private $pigisteClients;


    public function __construct()
    {
        $this->iconographiques = new ArrayCollection();
        $this->redachefs = new ArrayCollection();
        $this->pigisteClients = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeAffaire(): ?string
    {
        return $this->code_affaire;
    }

    public function setCodeAffaire(string $code_affaire): self
    {
        $this->code_affaire = $code_affaire;

        return $this;
    }

    public function getCodeAffaireEnClair(): ?string
    {
        return $this->code_affaire_en_clair;
    }

    public function setCodeAffaireEnClair(string $code_affaire_en_clair): self
    {
        $this->code_affaire_en_clair = $code_affaire_en_clair;

        return $this;
    }

    public function getDateDeBouclage(): ?string
    {
        return $this->date_de_bouclage;
    }

    public function setDateDeBouclage(?string $date_de_bouclage): self
    {
        $this->date_de_bouclage = $date_de_bouclage;

        return $this;
    }

    public function getDateDeParution(): ?string
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(?string $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getTitreEnClair(): ?string
    {
        return $this->titre_en_clair;
    }

    public function setTitreEnClair(?string $titre_en_clair): self
    {
        $this->titre_en_clair = $titre_en_clair;

        return $this;
    }

    /**
     * Get the value of nb_de_page_redactionnelle
     */
    public function getNbDePageRedactionnelle() : ?float
    {
        return $this->nb_de_page_redactionnelle;
    }

    /**
     * Set the value of nb_de_page_redactionnelle
     *
     * @return  self
     */
    public function setNbDePageRedactionnelle(?float $nb_de_page_redactionnelle): self
    {
        $this->nb_de_page_redactionnelle = $nb_de_page_redactionnelle;

        return $this;
    }

    public function getTitre(): ?Titre
    {
        return $this->titre;
    }

    public function setTitre(?Titre $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getChiffreAffaire() : ?float
    {
        return $this->chiffre_affaire;
    }
    public function setChiffreAffaire(?float $chiffre_affaire): self
    {
        $this->chiffre_affaire = $chiffre_affaire;

        return $this;
    }

    public function getRacine(): ?string {
        return $this->getTitre()?->getRacine();
    }

    public function __toString(): string {
        return "[" . $this->code_affaire . "] " . $this->code_affaire_en_clair;
    }

    /**
     * @return Collection<int, Redachef>
     */
    public function getRedachefs(): Collection
    {
        return $this->redachefs;
    }

    public function addRedachef(Redachef $redachef): self
    {
        if (!$this->redachefs->contains($redachef)) {
            $this->redachefs[] = $redachef;
            $redachef->setMagazine($this);
        }

        return $this;
    }

    public function removeRedachef(Redachef $redachef): self
    {
        if ($this->redachefs->removeElement($redachef)) {
            // set the owning side to null (unless already changed)
            if ($redachef->getMagazine() === $this) {
                $redachef->setMagazine(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Iconographique>
     */
    public function getIconographiques(): Collection
    {
        return $this->iconographiques;
    }

    public function addIconographique(Iconographique $iconographique): self
    {
        if (!$this->iconographiques->contains($iconographique)) {
            $this->iconographiques[] = $iconographique;
            $iconographique->setMagazine($this);
        }

        return $this;
    }

    public function removeIconographique(Iconographique $iconographique): self
    {
        if ($this->iconographiques->removeElement($iconographique)) {
            // set the owning side to null (unless already changed)
            if ($iconographique->getMagazine() === $this) {
                $iconographique->setMagazine(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PigisteClient>
     */
    public function getPigisteClients(): Collection
    {
        return $this->pigisteClients;
    }

    public function addPigisteClient(PigisteClient $pigisteClient): self
    {
        if (!$this->pigisteClients->contains($pigisteClient)) {
            $this->pigisteClients[] = $pigisteClient;
            $pigisteClient->setMagazine($this);
        }

        return $this;
    }

    public function removePigisteClient(PigisteClient $pigisteClient): self
    {
        if ($this->pigisteClients->removeElement($pigisteClient)) {
            // set the owning side to null (unless already changed)
            if ($pigisteClient->getMagazine() === $this) {
                $pigisteClient->setMagazine(null);
            }
        }

        return $this;
    }


    public function getDateDeParutionSetAt(): ?\DateTimeInterface
    {
        return $this->date_de_parution_set_at;
    }

    public function setDateDeParutionSetAt(?\DateTimeInterface $date_de_parution_set_at): self
    {
        $this->date_de_parution_set_at = $date_de_parution_set_at;

        return $this;
    }

    public function getDateDeBouclageSetAt(): ?\DateTimeInterface
    {
        return $this->date_de_bouclage_set_at;
    }

    public function setDateDeBouclageSetAt(?\DateTimeInterface $date_de_bouclage_set_at): self
    {
        $this->date_de_bouclage_set_at = $date_de_bouclage_set_at;

        return $this;
    }

    public function getNbDePageRedactionnelleSetAt(): ?\DateTimeInterface
    {
        return $this->nb_de_page_redactionnelle_set_at;
    }

    public  function setNbDePageRedactionnelleSetAt(?\DateTimeInterface $nb_de_page_redactionnelle_set_at): self
    {
        $this->nb_de_page_redactionnelle_set_at = $nb_de_page_redactionnelle_set_at;

        return $this;
    }

}

src/Entity/Redachef.php
<?php

namespace App\Entity;

use App\Entity\Magazine;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\SalarieEtEntreprise;
use App\Repository\RedachefRepository;

#[ORM\Entity(repositoryClass: RedachefRepository::class)]
class Redachef
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 63, nullable: true)]
    private $article;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $signe;

    #[ORM\Column(type: 'float', nullable: true)]
    private $nb_de_feuillet;

    #[ORM\Column(type: 'float', nullable: true)]
    private $forfait;

    #[ORM\Column(type: 'float', nullable: true)]
    private $prix_au_feuillet;

    #[ORM\Column(type: 'float')]
    private $montant;

    #[ORM\Column(type: 'float', nullable: true)]
    private $montant_total_brut;

    #[ORM\Column(type: 'float', nullable: true)]
    private $montant_charge;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\ManyToOne(targetEntity: Magazine::class, inversedBy: 'redachefs')]
    private $magazine;

    #[ORM\ManyToOne(targetEntity: SalarieEtEntreprise::class, inversedBy: 'redachefs')]
    private $salarie_et_entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticle(): ?string
    {
        return $this->article;
    }

    public function setArticle(?string $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getSigne(): ?int
    {
        return $this->signe;
    }

    public function setSigne(?int $signe): self
    {
        $this->signe = $signe;

        return $this;
    }

    public function getNbDeFeuillet(): ?float
    {
        return $this->nb_de_feuillet;
    }

    public function setNbDeFeuillet(?float $nb_de_feuillet): self
    {
        $this->nb_de_feuillet = $nb_de_feuillet;

        return $this;
    }

    public function getForfait(): ?float
    {
        return $this->forfait;
    }

    public function setForfait(?float $forfait): self
    {
        $this->forfait = $forfait;

        return $this;
    }

    public function getPrixAuFeuillet(): ?float
    {
        return $this->prix_au_feuillet;
    }

    public function setPrixAuFeuillet(?float $prix_au_feuillet): self
    {
        $this->prix_au_feuillet = $prix_au_feuillet;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getMontantTotalBrut(): ?float
    {
        return $this->montant_total_brut;
    }

    public function setMontantTotalBrut(?float $montant_total_brut): self
    {
        $this->montant_total_brut = $montant_total_brut;

        return $this;
    }

    public function getMontantCharge(): ?float
    {
        return $this->montant_charge;
    }

    public function setMontantCharge(?float $montant_charge): self
    {
        $this->montant_charge = $montant_charge;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getMagazine(): ?Magazine
    {
        return $this->magazine;
    }

    public function setMagazine(?Magazine $magazine): self
    {
        $this->magazine = $magazine;

        return $this;
    }

    public function getSalarieEtEntreprise(): ?SalarieEtEntreprise
    {
        return $this->salarie_et_entreprise;
    }

    public function setSalarieEtEntreprise(?SalarieEtEntreprise $salarie_et_entreprise): self
    {
        $this->salarie_et_entreprise = $salarie_et_entreprise;

        return $this;
    }
     // SalarieEtEntreprise attributes for Dashboard and Redachef view

     public function getNomDUsage(): string {
        return $this->getSalarieEtEntreprise()->getNomDUsage();
    }

    public function getNomCompta(): string {
        return $this->getSalarieEtEntreprise()->getNomCompta();
    }

    public function getStatut(): string {
        return $this->getSalarieEtEntreprise()->getStatut();
    }

    public function getType(): string {
        return $this->getSalarieEtEntreprise()->getType();
    }

    public function getCodeAffaire(): string {
        return $this->getMagazine()->getCodeAffaire();
    }

    public function getRacine(): ?string {
        return $this->getMagazine()->getTitre()?->getRacine();
    }

    
}

src/Controller/RedachefController.php
<?php

namespace App\Controller;

use App\Entity\Magazine;
use App\Entity\Redachef;

use App\Form\EditRedachefType;
use App\Repository\RedachefRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\SalarieEtEntrepriseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class RedachefController extends AbstractController
{
    #[Route('/magazine/{magazine}/redachef', name: 'app_redachef')]
    public function index(ManagerRegistry $doctrine, Magazine $magazine, Request $request, SalarieEtEntrepriseRepository $salarieRepo): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');//Imposible de voir le site si on est pas connecté

        $data = $request->get('data');
        if ($data != null) {
            $obj = json_decode($data);
            
            $entityManager = $doctrine->getManager();

            foreach ($obj as $item) {
                $salarie = $salarieRepo->find($item->salarie_id);

                if ($salarie == null) {
                    continue;
                }

                $redachef = new Redachef();
                $redachef->setSalarieEtEntreprise($salarie);
                $redachef->setMagazine($magazine);
                $redachef->setArticle($item->article);
                $redachef->setSigne($item->signe);
                $redachef->setNbDeFeuillet($item->nb_de_feuillet);
                $redachef->setForfait($item->forfait);
                $redachef->setPrixAuFeuillet($item->prix_au_feuillet);
                $redachef->setMontant($item->montant);
                $redachef->setCreatedAt(date_create());

                $entityManager->persist($redachef);
            }

            $entityManager->flush();
        }

        $redachef = $magazine->getRedachefs();


        return $this->render('redachef/index.html.twig', [
            'redachef' => $redachef,
            'magazine' => $magazine,
        ]);
    }

    #[Route('/magazine/{magazine}/redachef/{redachef}/edit', name: 'app_edit_redachef')]
    public function edit(Magazine $magazine, Redachef $redachef, Request $request, ManagerRegistry $doctrine,): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');//Imposible de voir le site si on est pas connecté

        $form = $this->createForm(EditRedachefType::class, $redachef);
        $form->handleRequest($request);

        $now = date_create();

        if ($form->isSubmitted() && $form->isValid()){
            if ($redachef->getCreatedAt()->diff($now)->days < 5) {
                $em = $doctrine->getManager();
                $em->persist($redachef);
                $em->flush();

                $this->addFlash('success', 'Redachef enregistrée avec succès');
            } else {
                $this->addFlash('danger', "Ce n'est pas possible de modifier le redachef");
            }

            return $this->redirectToRoute('app_redachef', ['magazine' => $magazine->getId()]);
        }

        return $this->render('redachef/edit.html.twig', [
            'redachef' => $redachef,
            'form' => $form->createView(),

        ]);
    }
}

templates/redachef/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Éditer Redachef - {{ redachef.article }}
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="/css/iconographique.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
{% endblock %}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{{ asset('javascript/app.js') }}" defer></script>
{% endblock %}
{% block body %}


    <div class="container mt-4 accueil-bg m-auto">
        {{ form(form) }}
    </div>
{% endblock %}

templates/redachef/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ magazine.codeAffaireEnClair }}
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="/css/iconographique.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
{% endblock %}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{{ asset('javascript/app.js') }}" defer></script>
{% endblock %}
{% block body %}
    {% include '_partials/_flash.html.twig' %}

    <div class="container accueil-bg m-auto">

        {% if app.user %}

            <div class="mb-3 Magazine">
                <h3>
                    </a>{{ magazine.codeAffaireEnClair }}
                </h3>
                <button type="button" class="btn btn-link">
                    <a class="nav-link" href="{{ path('app_choose_magazine_type', {'magazine': magazine.id}) }}">
                        « Page précédante
                    </a>
                </button>
            </div>
            <div class="col">
                <div class="col-md-12">
                    <form method="post" class="row" action="{{ path('app_magazine_set_nb_de_page_redactionnelle', {'magazine': magazine.id, 'origin': 'redachef'}) }}">
                        {% set cannotModifyNbDePageRedactionnelle = magazine.nbDePageRedactionnelleSetAt != null and date().diff(date(magazine.nbDePageRedactionnelleSetAt)).days >= 5 %}
                        <label for="nb_de_page_redactionnelle" class="col-md-3 col-form-label">Nombre de page redactionnelle</label>
                        <div class="col-md-6">
                            <input class="form-control" type="text" value="{{ magazine.nbDePageRedactionnelle }}" id="nb_de_page_redactionnelle" placeholder="Nombre de page redactionnelle" aria-label="Nombre de page redactionnelle" name="nb_de_page_redactionnelle" required {% if cannotModifyNbDePageRedactionnelle %} disabled {% endif %}>
                        </div>
                        <div class="col-md-3">
                            <button type="submit" class="btn btn-success w-100" {% if cannotModifyNbDePageRedactionnelle %} disabled {% endif %}>Enregistrer</button>
                        </div>
                    </form>
                </div>
            </div>
            <hr>

            <div class="container" style="position: relative; padding: 0">
                <div class="edit-tooltip" id="edit-tooltip" style="display: none"></div>
                <h1 class='text-center'>Rédac chef</h1>
                <input id="autocomplete-url" type="hidden" value="{{ path('app_salarie_et_entreprise_search') }}">
                <table class="table table-bordered table-dark" id="table">
                    <thead>
                    <tr>
                        <th scope="col" data-column="nom_d_usage">Nom d'usage</th>
                        <th scope="col" data-collapse-to="0" data-column="nom_compta">Nom compta</th>
                        <th scope="col" data-collapse-to="0" data-column="statut">Statut</th>
                        <th scope="col" data-collapse-to="0" data-column="type">Type</th>
                        <th scope="col" data-collapse-to="0" data-column="droit_auteur">Droit d'auteur</th>
                        <th scope="col" data-type="string" data-max-length="63" data-name="article">Article</th>
                        <th scope="col" data-type="int" data-max-length="11" data-name="signe">Signe</th>
                        <th scope="col" data-type="double" data-name="nb_de_feuillet">Nombre de feuillet</th>
                        <th scope="col" data-type="double" data-name="forfait">Forfait</th>
                        <th scope="col" data-type="double" data-name="prix_au_feuillet">Prix au feuillet</th>
                        <th scope="col" data-type="double" data-required="true" data-name="montant">Montant</th>
                        <th scope="col" data-buttons="true">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for aRedachef in redachef %}
                        <tr>
                            <td>{{ aRedachef.nomDUsage }}</td>
                            <td>{{ aRedachef.nomCompta }}</td>
                            <td>{{ aRedachef.statut }}</td>
                            <td>{{ aRedachef.type }}</td>
                            <td>{{ aRedachef.salarieEtEntreprise.droitAuteur }}</td>
                            <td>{{ aRedachef.article }}</td>
                            <td>{{ aRedachef.signe }}</td>
                            <td>{{ aRedachef.nbDeFeuillet }} </td>
                            <td>{{ aRedachef.forfait }}</td>
                            <td>{{ aRedachef.prixAuFeuillet }}</td>
                            <td>{{ aRedachef.montant|format_currency('EUR') }}</td>
                            <td style="text-align: center">
                                {% if date().diff(date(aRedachef.createdAt)).days < 5 %}
                                    <a href="{{ path('app_edit_redachef', {'redachef': aRedachef.id, 'magazine': magazine.id}) }}">
                                        <button class="btn btn-warning btn-sm" data-bs-toggle="tooltip" data-bs-title="Éditer">
                                            <i class="fa fa-pencil"></i>
                                        </button>
                                    </a>
                                {% else %}
                                    <button class="btn btn-warning btn-sm" data-bs-toggle="tooltip" data-bs-title="Éditer" disabled>
                                        <i class="fa fa-pencil"></i>
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    <tr class="text-center add-row" id="add_row">
                        <td colspan="12">
                            <span>+</span>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <form method="post" id="data-form" action="{{ path('app_redachef', {'magazine': magazine.id}) }}">
                        <input type="hidden" name="data" id="data-input">
                        <button class="btn btn-success float-right" type="submit">
                            Enregistrer
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}