src/Entity/Magazine.php
<?php

namespace App\Entity;


use App\Entity\Titre;
use App\Entity\Redachef;
use App\Entity\Iconographique;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MagazineRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;



#[ORM\Entity(repositoryClass: MagazineRepository::class)]
/**  @ORM\Table(name="magazine", indexes={@ORM\Index(columns={"code_affaire", "code_affaire_en_clair"}, flags={"fulltext"})}) */

class Magazine
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 63)]
    private $code_affaire;

    #[ORM\Column(type: 'string', length: 255)]
    private $code_affaire_en_clair;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $date_de_bouclage;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $date_de_parution;

    #[ORM\Column(type: 'string', length: 127, nullable: true)]
    private $titre_en_clair;

    #[ORM\Column(type: 'float', length: 63, nullable: true)]
    private $nb_de_page_redactionnelle;

    #[ORM\ManyToOne(targetEntity: Titre::class, inversedBy: 'magazines')]
    #[ORM\JoinColumn(nullable: true)]
    private $titre;

    #[ORM\Column(type: 'float', length: 63, nullable: true)]
    private $chiffre_affaire;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_de_parution_set_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_de_bouclage_set_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $nb_de_page_redactionnelle_set_at;

    #[ORM\OneToMany(mappedBy: 'magazine', targetEntity: Redachef::class)]
    private $redachefs;

    #[ORM\OneToMany(mappedBy: 'magazine', targetEntity: Iconographique::class)]
    private $iconographiques;

    #[ORM\OneToMany(mappedBy: 'magazine', targetEntity: PigisteClient::class)]
    private $pigisteClients;


    public function __construct()
    {
        $this->iconographiques = new ArrayCollection();
        $this->redachefs = new ArrayCollection();
        $this->pigisteClients = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeAffaire(): ?string
    {
        return $this->code_affaire;
    }

    public function setCodeAffaire(string $code_affaire): self
    {
        $this->code_affaire = $code_affaire;

        return $this;
    }

    public function getCodeAffaireEnClair(): ?string
    {
        return $this->code_affaire_en_clair;
    }

    public function setCodeAffaireEnClair(string $code_affaire_en_clair): self
    {
        $this->code_affaire_en_clair = $code_affaire_en_clair;

        return $this;
    }

    public function getDateDeBouclage(): ?string
    {
        return $this->date_de_bouclage;
    }

    public function setDateDeBouclage(?string $date_de_bouclage): self
    {
        $this->date_de_bouclage = $date_de_bouclage;

        return $this;
    }

    public function getDateDeParution(): ?string
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(?string $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getTitreEnClair(): ?string
    {
        return $this->titre_en_clair;
    }

    public function setTitreEnClair(?string $titre_en_clair): self
    {
        $this->titre_en_clair = $titre_en_clair;

        return $this;
    }

    /**
     * Get the value of nb_de_page_redactionnelle
     */
    public function getNbDePageRedactionnelle() : ?float
    {
        return $this->nb_de_page_redactionnelle;
    }

    /**
     * Set the value of nb_de_page_redactionnelle
     *
     * @return  self
     */
    public function setNbDePageRedactionnelle(?float $nb_de_page_redactionnelle): self
    {
        $this->nb_de_page_redactionnelle = $nb_de_page_redactionnelle;

        return $this;
    }

    public function getTitre(): ?Titre
    {
        return $this->titre;
    }

    public function setTitre(?Titre $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getChiffreAffaire() : ?float
    {
        return $this->chiffre_affaire;
    }
    public function setChiffreAffaire(?float $chiffre_affaire): self
    {
        $this->chiffre_affaire = $chiffre_affaire;

        return $this;
    }

    public function getRacine(): ?string {
        return $this->getTitre()?->getRacine();
    }

    public function __toString(): string {
        return "[" . $this->code_affaire . "] " . $this->code_affaire_en_clair;
    }

    /**
     * @return Collection<int, Redachef>
     */
    public function getRedachefs(): Collection
    {
        return $this->redachefs;
    }

    public function addRedachef(Redachef $redachef): self
    {
        if (!$this->redachefs->contains($redachef)) {
            $this->redachefs[] = $redachef;
            $redachef->setMagazine($this);
        }

        return $this;
    }

    public function removeRedachef(Redachef $redachef): self
    {
        if ($this->redachefs->removeElement($redachef)) {
            // set the owning side to null (unless already changed)
            if ($redachef->getMagazine() === $this) {
                $redachef->setMagazine(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Iconographique>
     */
    public function getIconographiques(): Collection
    {
        return $this->iconographiques;
    }

    public function addIconographique(Iconographique $iconographique): self
    {
        if (!$this->iconographiques->contains($iconographique)) {
            $this->iconographiques[] = $iconographique;
            $iconographique->setMagazine($this);
        }

        return $this;
    }

    public function removeIconographique(Iconographique $iconographique): self
    {
        if ($this->iconographiques->removeElement($iconographique)) {
            // set the owning side to null (unless already changed)
            if ($iconographique->getMagazine() === $this) {
                $iconographique->setMagazine(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PigisteClient>
     */
    public function getPigisteClients(): Collection
    {
        return $this->pigisteClients;
    }

    public function addPigisteClient(PigisteClient $pigisteClient): self
    {
        if (!$this->pigisteClients->contains($pigisteClient)) {
            $this->pigisteClients[] = $pigisteClient;
            $pigisteClient->setMagazine($this);
        }

        return $this;
    }

    public function removePigisteClient(PigisteClient $pigisteClient): self
    {
        if ($this->pigisteClients->removeElement($pigisteClient)) {
            // set the owning side to null (unless already changed)
            if ($pigisteClient->getMagazine() === $this) {
                $pigisteClient->setMagazine(null);
            }
        }

        return $this;
    }


    public function getDateDeParutionSetAt(): ?\DateTimeInterface
    {
        return $this->date_de_parution_set_at;
    }

    public function setDateDeParutionSetAt(?\DateTimeInterface $date_de_parution_set_at): self
    {
        $this->date_de_parution_set_at = $date_de_parution_set_at;

        return $this;
    }

    public function getDateDeBouclageSetAt(): ?\DateTimeInterface
    {
        return $this->date_de_bouclage_set_at;
    }

    public function setDateDeBouclageSetAt(?\DateTimeInterface $date_de_bouclage_set_at): self
    {
        $this->date_de_bouclage_set_at = $date_de_bouclage_set_at;

        return $this;
    }

    public function getNbDePageRedactionnelleSetAt(): ?\DateTimeInterface
    {
        return $this->nb_de_page_redactionnelle_set_at;
    }

    public  function setNbDePageRedactionnelleSetAt(?\DateTimeInterface $nb_de_page_redactionnelle_set_at): self
    {
        $this->nb_de_page_redactionnelle_set_at = $nb_de_page_redactionnelle_set_at;

        return $this;
    }

}

src/Entity/Redachef.php
<?php

namespace App\Entity;

use App\Entity\Magazine;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\SalarieEtEntreprise;
use App\Repository\RedachefRepository;

#[ORM\Entity(repositoryClass: RedachefRepository::class)]
class Redachef
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 63, nullable: true)]
    private $article;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $signe;

    #[ORM\Column(type: 'float', nullable: true)]
    private $nb_de_feuillet;

    #[ORM\Column(type: 'float', nullable: true)]
    private $forfait;

    #[ORM\Column(type: 'float', nullable: true)]
    private $prix_au_feuillet;

    #[ORM\Column(type: 'float')]
    private $montant;

    #[ORM\Column(type: 'float', nullable: true)]
    private $montant_total_brut;

    #[ORM\Column(type: 'float', nullable: true)]
    private $montant_charge;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\ManyToOne(targetEntity: Magazine::class, inversedBy: 'redachefs')]
    private $magazine;

    #[ORM\ManyToOne(targetEntity: SalarieEtEntreprise::class, inversedBy: 'redachefs')]
    private $salarie_et_entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticle(): ?string
    {
        return $this->article;
    }

    public function setArticle(?string $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getSigne(): ?int
    {
        return $this->signe;
    }

    public function setSigne(?int $signe): self
    {
        $this->signe = $signe;

        return $this;
    }

    public function getNbDeFeuillet(): ?float
    {
        return $this->nb_de_feuillet;
    }

    public function setNbDeFeuillet(?float $nb_de_feuillet): self
    {
        $this->nb_de_feuillet = $nb_de_feuillet;

        return $this;
    }

    public function getForfait(): ?float
    {
        return $this->forfait;
    }

    public function setForfait(?float $forfait): self
    {
        $this->forfait = $forfait;

        return $this;
    }

    public function getPrixAuFeuillet(): ?float
    {
        return $this->prix_au_feuillet;
    }

    public function setPrixAuFeuillet(?float $prix_au_feuillet): self
    {
        $this->prix_au_feuillet = $prix_au_feuillet;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getMontantTotalBrut(): ?float
    {
        return $this->montant_total_brut;
    }

    public function setMontantTotalBrut(?float $montant_total_brut): self
    {
        $this->montant_total_brut = $montant_total_brut;

        return $this;
    }

    public function getMontantCharge(): ?float
    {
        return $this->montant_charge;
    }

    public function setMontantCharge(?float $montant_charge): self
    {
        $this->montant_charge = $montant_charge;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getMagazine(): ?Magazine
    {
        return $this->magazine;
    }

    public function setMagazine(?Magazine $magazine): self
    {
        $this->magazine = $magazine;

        return $this;
    }

    public function getSalarieEtEntreprise(): ?SalarieEtEntreprise
    {
        return $this->salarie_et_entreprise;
    }

    public function setSalarieEtEntreprise(?SalarieEtEntreprise $salarie_et_entreprise): self
    {
        $this->salarie_et_entreprise = $salarie_et_entreprise;

        return $this;
    }
     // SalarieEtEntreprise attributes for Dashboard and Redachef view

     public function getNomDUsage(): string {
        return $this->getSalarieEtEntreprise()->getNomDUsage();
    }

    public function getNomCompta(): string {
        return $this->getSalarieEtEntreprise()->getNomCompta();
    }

    public function getStatut(): string {
        return $this->getSalarieEtEntreprise()->getStatut();
    }

    public function getType(): string {
        return $this->getSalarieEtEntreprise()->getType();
    }

    public function getCodeAffaire(): string {
        return $this->getMagazine()->getCodeAffaire();
    }

    public function getRacine(): ?string {
        return $this->getMagazine()->getTitre()?->getRacine();
    }

    
}

src/Entity/Titre.php
<?php

namespace App\Entity;

use App\Repository\TitreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TitreRepository::class)]
class Titre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 127)]
    private $titre_dans_tableau_direction;

    #[ORM\Column(type: 'string', length: 63)]
    private $clients;

    #[ORM\Column(type: 'string', length: 15)]
    private $racine;

    #[ORM\Column(type: 'string', length: 127)]
    private $racine_en_clair;

    #[ORM\OneToMany(mappedBy: 'titre', targetEntity: Magazine::class)]
    private $magazines;

    #[ORM\OneToMany(mappedBy: 'titre', targetEntity: TitreMembership::class)]
    private $titreMemberships;

    public function __construct()
    {
        $this->magazines = new ArrayCollection();
        $this->titreMemberships = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreDansTableauDirection(): ?string
    {
        return $this->titre_dans_tableau_direction;
    }

    public function setTitreDansTableauDirection(string $titre_dans_tableau_direction): self
    {
        $this->titre_dans_tableau_direction = $titre_dans_tableau_direction;

        return $this;
    }

    public function getClients(): ?string
    {
        return $this->clients;
    }

    public function setClients(string $clients): self
    {
        $this->clients = $clients;

        return $this;
    }

    public function getRacine(): ?string
    {
        return $this->racine;
    }

    public function setRacine(string $racine): self
    {
        $this->racine = $racine;

        return $this;
    }

    public function getRacineEnClair(): ?string
    {
        return $this->racine_en_clair;
    }

    public function setRacineEnClair(string $racine_en_clair): self
    {
        $this->racine_en_clair = $racine_en_clair;

        return $this;
    }

    /**
     * @return Collection<int, Magazine>
     */
    public function getMagazines(): Collection
    {
        return $this->magazines;
    }

    public function addMagazine(Magazine $magazine): self
    {
        if (!$this->magazines->contains($magazine)) {
            $this->magazines[] = $magazine;
            $magazine->setTitre($this);
        }

        return $this;
    }

    public function removeMagazine(Magazine $magazine): self
    {
        if ($this->magazines->removeElement($magazine)) {
            // set the owning side to null (unless already changed)
            if ($magazine->getTitre() === $this) {
                $magazine->setTitre(null);
            }
        }

        return $this;
    }
    
    public function __toString(): string {
        return "[" . $this->getRacine() . "] " . $this->getTitreDansTableauDirection();
    }

    /**
     * @return Collection<int, TitreMembership>
     */
    public function getTitreMemberships(): Collection
    {
        return $this->titreMemberships;
    }

    public function addTitreMembership(TitreMembership $titreMembership): self
    {
        if (!$this->titreMemberships->contains($titreMembership)) {
            $this->titreMemberships[] = $titreMembership;
            $titreMembership->setTitre($this);
        }

        return $this;
    }

    public function removeTitreMembership(TitreMembership $titreMembership): self
    {
        if ($this->titreMemberships->removeElement($titreMembership)) {
            // set the owning side to null (unless already changed)
            if ($titreMembership->getTitre() === $this) {
                $titreMembership->setTitre(null);
            }
        }

        return $this;
    }
}

templates/titre/detail_view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ magazine.codeAffaireEnClair }}{% endblock %}

{% block body %}
    <div class="container accueil-bg m-auto">

        {% if app.user %}

            {# <form method="get">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Entrez nom du titre ou le nom du client" name="mots" value="{{ mots }}">
                </div>
                <div class="form-group mt-2">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </form>#}

            <div class="container">
                <h1 class='text-center'>Détail {{ magazine.codeAffaireEnClair }}</h1>
                <table class="table table-striped">


                    <thead class="">
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">Statut</th>
                        <th scope="col">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% set totalCharged = 0 %}

                    {% for salarieEtEntreprise in salarie_et_entreprises %}
                        <tr>
                            <td>
                                {{ salarieEtEntreprise.nom_d_usage }}
                            </td>
                            <td>
                                {{ salarieEtEntreprise.statut }}
                            </td>
                            <td>
                                {% set totalCharged =  totalCharged + salarieEtEntreprise.total %}
                                {{ salarieEtEntreprise.total|format_currency('EUR')  }}
                            </td>
                        </tr>
                    {% endfor %}

                    <tr>
                        <td colspan="2"><strong>TOTAL</strong></td>
                        <td><strong>{{ totalCharged|format_currency('EUR') }}</strong></td>
                        <td colspan="2"></td>
                    </tr>
                    </tbody>
                </table>

            </div>
        {% endif %}

    </div>

{% endblock %}

templates/titre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Titres{% endblock %}

{% block body %}
    {% include '_partials/_flash.html.twig' %}

    <div class="container accueil-bg m-auto">

        {% if app.user %}

                <form method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Entrez nom du titre ou le nom du client" name="mots" value="{{ mots }}">
                    </div>
                    <div class="form-group mt-2">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </form>

                <div class="container">
                    <h1 class='text-center'>Recherchez le titre</h1>
                    <table class="table table-striped">


                        <thead class="">
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Titre dans tableau direction</th>
                            <th scope="col">Client</th>
                            <th scope="col">Racine</th>
                            <th scope="col">Racine en clair</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for aTitre in titre %}
                            <tr>
                                <td>
                                    {{ aTitre.id }}
                                </td>
                                <td>
                                    {{ aTitre.titreDansTableauDirection }}
                                </td>
                                <td>
                                    {{ aTitre.clients }}
                                </td>
                                <td>
                                    {{ aTitre.racine }}
                                </td>
                                <td>
                                    {{ aTitre.racineEnClair }}
                                </td>
                                <td>
                                    <a href="{{ path('app_choose_titre_details', {'titre': aTitre.id}) }}">
                                        <button class="btn btn-outline-primary">Choisir</button>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}
                        </tbody>
                    </table>
                    {{ knp_pagination_render(titre) }}
                </div>
            {% endif %}

    </div>
{% endblock %}

templates/titre/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ titre.titreDansTableauDirection }}{% endblock %}

{% block body %}
    <div class="container accueil-bg m-auto">

        {% if app.user %}

            {# <form method="get">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Entrez nom du titre ou le nom du client" name="mots" value="{{ mots }}">
                </div>
                <div class="form-group mt-2">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </form>#}

            <div class="container">
                <h1 class='text-center'>Détails</h1>
                <table class="table table-striped">


                    <thead class="">
                    <tr>
                        <th scope="col">Magazine en clair</th>
                        <th scope="col">Code Affaire</th>
                        <th scope="col">CA</th>
                        <th scope="col">Charge</th>
                        <th scope="col">Resultat</th>
                        <th scope="col">%</th>
                        <th scope="col">Détails</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% set totalCA = 0 %}
                    {% set totalCharged = 0 %}
                    {% set totalResult = 0 %}
                    {% for aMagazine in magazine %}
                        <tr>
                            <td>
                                {{ aMagazine.codeAffaireEnClair }}
                            </td>
                            <td>
                                {{ aMagazine.codeAffaire }}
                            </td>
                            <td>
                                {% set totalCA = totalCA + aMagazine.chiffreAffaire %}

                                {{ aMagazine.chiffreAffaire|format_currency('EUR') }}
                            </td>
                            <td>
                                {% set charged = 0 %}
                                {% for redachef in aMagazine.redachefs %}
                                    {% set charged = charged + redachef.montant %}
                                {% endfor %}
                                {% for iconographique in aMagazine.iconographiques %}
                                    {% set charged = charged + iconographique.montant %}
                                {% endfor %}
                                {% for pigisteClient in aMagazine.pigisteClients %}
                                    {% set charged = charged + pigisteClient.montant %}
                                {% endfor %}

                                {% set totalCharged = totalCharged + charged %}

                                {{ charged|format_currency('EUR') }}
                            </td>
                            <td>
                                {% set result = aMagazine.chiffreAffaire - charged %}

                                {% set totalResult = totalResult + result %}

                                {{ result|format_currency('EUR') }}
                            </td>
                            <td>
                                {% if aMagazine.chiffreAffaire %}
                                    {{ (result / aMagazine.chiffreAffaire)|format_percent_number({fraction_digit: 2}) }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                               <a href="{{ path('app_view_details_by_magazine', {'titre': titre.id, 'magazine': aMagazine.id}) }}">

                                <button class="btn btn-outline-primary">Voir détails</button>
                               </a>
                            </td>
                        </tr>

                    {% endfor %}

                    <tr>
                        <td colspan="2"><strong>TOTAL</strong></td>
                        <td><strong>{{ totalCA|format_currency('EUR') }}</strong></td>
                        <td><strong>{{ totalCharged|format_currency('EUR') }}</strong></td>
                        <td><strong>{{ totalResult|format_currency('EUR') }}</strong></td>
                        <td colspan="2"></td>
                    </tr>
                    </tbody>
                </table>
                {{ knp_pagination_render(magazine) }}
            </div>
        {% endif %}

    </div>

{% endblock %}